### ISSUE TITLE
请问这个是不是只有对小数据集训练的代码？

### ISSUE THREAD

**Issue by han9979** [Zhankun-Xiong/MRCGNN#2]
请问可以提供一下第二个数据集的代码吗？

**Comment by han9979** [comment]
请问可以提供一下第二个数据集的代码吗？

**Comment by Zhankun-Xiong** [comment]
您好，对于两个数据集的训练代码基本上一样，所以仅以第一个数据集为例上传了代码，您修改一下数据路径和分类类型数量等参数即可：）

**Comment by han9979** [comment]
谢谢您的回复！我的代码能力比较薄弱，请问具体需要修改哪些参数呀？我在自己改的时候遇到了这个错误Traceback (most recent call last):
  File "I:\code\MRCGNN-main\codes for MRCGNN\main2.py", line 30, in <module>
    data_o, data_s, data_a, train_loader, val_loader, test_loader = load_data(args)
  File "I:\code\MRCGNN-main\codes for MRCGNN\data_preprocess2.py", line 161, in load_data
    features1.append(features[ids.index(drug_list[i])])
ValueError: 'drug_id' is not in list.
目前遇到了解决困难。再次感谢您的回复，期待您的解答，万分感谢！

**Comment by Zhankun-Xiong** [comment]
> 谢谢您的回复！我的代码能力比较薄弱，请问具体需要修改哪些参数呀？我在自己改的时候遇到了这个错误Traceback (most recent call last): File "I:\code\MRCGNN-main\codes for MRCGNN\main2.py", line 30, in data_o, data_s, data_a, train_loader, val_loader, test_loader = load_data(args) File "I:\code\MRCGNN-main\codes for MRCGNN\data_preprocess2.py", line 161, in load_data features1.append(features[ids.index(drug_list[i])]) ValueError: 'drug_id' is not in list. 目前遇到了解决困难。再次感谢您的回复，期待您的解答，万分感谢！

这个的话就是读取的那个csv文件里有个“drug_id”的列名没有删掉导致的，在数据中删掉就可以了

**Comment by han9979** [comment]
谢谢您的回复，上一个问题已经解决，现在出现了维度问题，Traceback (most recent call last):
  File "I:\code\MRCGNN-main\codes for MRCGNN\main2.py", line 30, in <module>
    data_o, data_s, data_a, train_loader, val_loader, test_loader = load_data(args)
  File "I:\code\MRCGNN-main\codes for MRCGNN\data_preprocess2.py", line 155, in load_data
    features1.append(features[ids.index(drug_list[i])])
IndexError: index 1586 is out of bounds for axis 0 with size 572。请问使用第二个数据集的话是不是trimnet中所有数据处理生成的东西全部需要改变呀？再次谢谢您的回复！！

**Comment by Zhankun-Xiong** [comment]
> 谢谢您的回复，上一个问题已经解决，现在出现了维度问题，Traceback (most recent call last): File "I:\code\MRCGNN-main\codes for MRCGNN\main2.py", line 30, in data_o, data_s, data_a, train_loader, val_loader, test_loader = load_data(args) File "I:\code\MRCGNN-main\codes for MRCGNN\data_preprocess2.py", line 155, in load_data features1.append(features[ids.index(drug_list[i])]) IndexError: index 1586 is out of bounds for axis 0 with size 572。请问使用第二个数据集的话是不是trimnet中所有数据处理生成的东西全部需要改变呀？再次谢谢您的回复！！

是的，毕竟药物总数也改变了

**Comment by han9979** [comment]
谢谢您的回复，上一个问题已经解决，现在出现了维度问题，Traceback (most recent call last):
  File "I:\code\MRCGNN-main\codes for MRCGNN\main2.py", line 30, in <module>
    data_o, data_s, data_a, train_loader, val_loader, test_loader = load_data(args)
  File "I:\code\MRCGNN-main\codes for MRCGNN\data_preprocess2.py", line 155, in load_data
    features1.append(features[ids.index(drug_list[i])])
IndexError: index 1586 is out of bounds for axis 0 with size 572请问使用第二个数据集的话是不是trimnet中所有数据处理生成的东西全部需要改变呀？再次谢谢您的回复！！

**Comment by han9979** [comment]
谢谢您啊，现在是我的设备问题了，数据处理跑不动了，十分感谢哈！
